# Generated by Django 5.1.4 on 2024-12-22 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка мащаины')),
                ('entry_time', models.DateTimeField(verbose_name='Дата и время въезда')),
                ('parking_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость стоянки')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Размер скиидки')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Задолженность')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
